# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "ybdesire"
repo_name: "cv-arxiv-daily-vul-llm"
show_authors: True
show_links: True
show_badge: True
max_results: 50

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "LLM-Malware-Detect": 
        filters: ["Code Malicious Detection LLM", "Malicious Detection LLM"]
    "LLM-Malware-Data":
        filters: ["Code Malicious Detection data LLM"]
    "LLM-Agent-Malware-Detect":
        filters: ["Threat Hunting LLM","Threat Hunting Agent LLM"]
    
